-- CronSmith task extension schema for H2.
--
-- Every table is prefixed cs_. The prefix is configurable at runtime through
-- TaskTables, so a deployment that needs a different one must adjust both.
--
-- All timestamps are stored in UTC; see com.github.cronsmith.extension.Settings.

DROP TABLE IF EXISTS cs_task_detail;
CREATE TABLE cs_task_detail (
    task_group          VARCHAR(255)  NOT NULL,
    task_name           VARCHAR(255)  NOT NULL,
    task_class          VARCHAR(255),
    task_method         VARCHAR(255),
    url                 VARCHAR(1024),
    description         VARCHAR(1024),
    initial_parameter   CLOB,
    -- The serialized expression is what the scheduler computes from; the text form beside it is
    -- for people reading the table, and for rebuilding the task if the binary form cannot be read.
    cron_expression     BLOB          NOT NULL,
    cron                VARCHAR(255)  NOT NULL,
    next_fired_datetime TIMESTAMP,
    prev_fired_datetime TIMESTAMP,
    task_status         VARCHAR(45)   NOT NULL,
    misfire_policy      VARCHAR(45)   NOT NULL DEFAULT 'FIRE_ONCE_NOW',
    max_retry_count     INT           NOT NULL DEFAULT 0,
    retry_interval      BIGINT        NOT NULL DEFAULT 1000,
    timeout             BIGINT        NOT NULL DEFAULT -1,
    run_count           BIGINT        NOT NULL DEFAULT 0,
    failure_count       BIGINT        NOT NULL DEFAULT 0,
    misfire_count       BIGINT        NOT NULL DEFAULT 0,
    last_modified       TIMESTAMP     NOT NULL,
    PRIMARY KEY (task_group, task_name)
);

-- Supports the clustered scheduler's "what is due now" query, and the console's status filter.
CREATE INDEX idx_cs_task_detail_next_fired ON cs_task_detail (next_fired_datetime);
CREATE INDEX idx_cs_task_detail_status ON cs_task_detail (task_status);

DROP TABLE IF EXISTS cs_task_log;
CREATE TABLE cs_task_log (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_group          VARCHAR(255)  NOT NULL,
    task_name           VARCHAR(255)  NOT NULL,
    -- When the run was due, as opposed to when it started: the gap between the two is the
    -- scheduling delay, which is the number worth watching.
    scheduled_datetime  TIMESTAMP     NOT NULL,
    fired_datetime      TIMESTAMP,
    completed_datetime  TIMESTAMP,
    return_value        CLOB,
    error_detail        CLOB,
    elapsed             BIGINT        NOT NULL DEFAULT 0,
    attempt             INT           NOT NULL DEFAULT 0,
    success             BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_cs_task_log_task ON cs_task_log (task_group, task_name, scheduled_datetime DESC);
