-- CronSmith task extension schema for Oracle 12c and later.
--
-- Mirrors cronsmith-schema-h2.sql; see that file for what the columns mean.
--
-- Note that running against Oracle needs a commercial JOOQ edition: the open source distribution
-- does not include the Oracle dialect. The DDL is here so a licensed deployment has it to hand.
--
-- Identifiers are left unquoted, so Oracle folds them to upper case, which is what JOOQ's unquoted
-- rendering resolves to as well.

CREATE TABLE cs_task_detail (
    task_group          VARCHAR2(255)  NOT NULL,
    task_name           VARCHAR2(255)  NOT NULL,
    task_class          VARCHAR2(255),
    task_method         VARCHAR2(255),
    url                 VARCHAR2(1024),
    description         VARCHAR2(1024),
    initial_parameter   CLOB,
    cron_expression     BLOB           NOT NULL,
    cron                VARCHAR2(255)  NOT NULL,
    next_fired_datetime TIMESTAMP,
    prev_fired_datetime TIMESTAMP,
    task_status         VARCHAR2(45)   NOT NULL,
    misfire_policy      VARCHAR2(45)   DEFAULT 'FIRE_ONCE_NOW' NOT NULL,
    max_retry_count     NUMBER(10)     DEFAULT 0 NOT NULL,
    retry_interval      NUMBER(19)     DEFAULT 1000 NOT NULL,
    timeout             NUMBER(19)     DEFAULT -1 NOT NULL,
    run_count           NUMBER(19)     DEFAULT 0 NOT NULL,
    failure_count       NUMBER(19)     DEFAULT 0 NOT NULL,
    misfire_count       NUMBER(19)     DEFAULT 0 NOT NULL,
    last_modified       TIMESTAMP      NOT NULL,
    CONSTRAINT pk_cs_task_detail PRIMARY KEY (task_group, task_name)
);

CREATE INDEX idx_cs_task_detail_next_fired ON cs_task_detail (next_fired_datetime);
CREATE INDEX idx_cs_task_detail_status ON cs_task_detail (task_status);

CREATE TABLE cs_task_log (
    id                  NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    task_group          VARCHAR2(255)  NOT NULL,
    task_name           VARCHAR2(255)  NOT NULL,
    scheduled_datetime  TIMESTAMP      NOT NULL,
    fired_datetime      TIMESTAMP,
    completed_datetime  TIMESTAMP,
    return_value        CLOB,
    error_detail        CLOB,
    elapsed             NUMBER(19)     DEFAULT 0 NOT NULL,
    attempt             NUMBER(10)     DEFAULT 0 NOT NULL,
    -- Oracle has no boolean column type before 23c; 0 and 1 are what JOOQ binds a Boolean to.
    success             NUMBER(1)      DEFAULT 0 NOT NULL,
    CONSTRAINT pk_cs_task_log PRIMARY KEY (id)
);

CREATE INDEX idx_cs_task_log_task ON cs_task_log (task_group, task_name, scheduled_datetime DESC);
